# Generated by Django 3.0.2 on 2020-02-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uVote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election_race',
            name='election_status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='voting_register',
            name='vote',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=20),
        ),
    ]
